### PR TITLE
cernlib: new formula

### PR DESCRIPTION
**Pull request by andriish**
*Cernlib

### Have you:

- [+] Run `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting) and corrected all errors?
- [+] Built your formula locally prior to submission with `brew install <formula>`?

### New formula: have you

- [+] Written a sensible test? (The best test is to compile and run a sample program.)

### CODE REVIEW

**Comment by andriish** [comment]
Hi @ebothmann ,


would you have a look?


Andrii

**Comment by andriish** [comment]
Hi @ebothmann , @davidchall ,

do you know what might be the reason of the error on macos-10.5 ?
It looks like a generic problem.

Best regards,

Andrii

**Comment by davidchall** [comment]
Hi @andriish - thanks for the PR!

I think the problem is caused by a typo in one the dependencies. It should be lowercase - I also received an error 404 if I tried to access the file, but this was resolved when I used a lowercase formula name.

**Comment by andriish** [comment]
Thank you, @davidchall !

**Comment by davidchall** [comment]
Hi @andriish  - I made some minor edits to conform to standards followed by other homebrew-hep formulae, and I added in the ctest step that I can see you attempted in previous commits.

My main feedback is that I'd prefer to have a meaningful test block for this formula. I don't use CERNLIB, so I couldn't tell if my local installation was working correctly. How do you plan to use it? Can you call any of the executables in the bin directory?

P.S. Please do not merge this PR directly. To build bottles, we instead add the "pr-pull" label to the PR, and the bot will merge it automatically.

**Comment by andriish** [comment]
Hi @davidchall ,
thank you very much for the update!

Execution of a reasonable executable would be problematic -- cernlib has either very complex executables or just plain libs and one would have to compile something.  But there is a `cernlib` script. Hopefully, it is fine.
However I don't understand if the `test` part is executed after the build or after the installation, so I've assumed that it will be executed after the installation. 


Best regards,

Andrii

**Comment by andriish** [comment]
Hi @davidchall , 

it seems there is a problem with configuration of the homebrew. Some complains about config files.
Could you, please, have a look?

Best regards,

Andrii

**Comment by davidchall** [comment]
@andriish - looks like the Homebrew issue will be fixed by https://github.com/Homebrew/brew/pull/14185. We'll need to wait for this to be merged and then rerun the CI builds.

**Comment by andriish** [comment]
Hi @davidchall ,

it looks it was merged. Hopefully the things are working now.


Andrii

**Comment by davidchall** [comment]
Hi @andriish,

That's right! The CI builds for this PR are now running smoothly again. You can click the "Checks" tab to see the results.

BTW - since the patch is quite large, could you please store it in a gist? (like you did in the [topdrawer](https://github.com/davidchall/homebrew-hep/blob/2e88ff4527ae448eaf397581dde0ef6845756342/Formula/topdrawer.rb#L31) formula)

Cheers, David

**Comment by andriish** [comment]
Hi @davidchall ,

done, the tests are running again with the gist!

Best regards,

Andrii

**Comment by andriish** [comment]
Hi @davidchall , @ebothmann ,

it looks fine. Finaly.

Andrii

**Pull request closed without merging**
