### PR TITLE
herwig: 7.0.2, thepeg: 2.0.2

### PR DESCRIPTION
**Pull request by veprbl**
My understanding is that Herwig 7 is a drop in replacement for Herwig++, so here is an update for the formula. Thank you for continuous support of homebrew-hep.

### CODE REVIEW

**Comment by veprbl** [comment]
Looks like Rivet-2.4.3.tar.gz was replaced upstream. Do you have original saved to compare? You can look in ```~/Library/Caches/Homebrew/```

**Comment by cjohnson-phys** [comment]
Hi veprbl,

Awesome work updating herwig to v7!

It would be really helpful to add --with-openloops and --with-madgraph options (this would be trivial). But even more so it would be nice to have a --with-vbfnlo option. This would obviously require creating a new formula. Having this formula would be a nice addition anyways.

I have been working on creating a formula for it but I have been running into trouble with the configure script not finding the proper fortran location. Could you possibly have a look it if you have the time?

Cheers,
Alex

**Comment by veprbl** [comment]
This doesn't seem to be such a big update. More like rebranding :)

As for fortran problem, try adding ```ENV.delete("F77")``` before configure step.

**Comment by veprbl** [comment]
I assume you already have ```depends_on :fortran```

**Comment by cjohnson-phys** [comment]
Yeah I do have that dependency already. And unfortunately the `ENV.delete("F77")` did not work.

Here is my current version of the formula:
```
class Vbfnlo < Formula
  homepage "https://www.itp.kit.edu/vbfnlo/wiki/doku.php?id=overview"
  version "3.0.0beta2"
  url "https://www.itp.kit.edu/vbfnlo/wiki/lib/exe/fetch.php?media=download:vbfnlo-#{version}.tgz"
  sha256 "c4b998f7541f0b192da69ee47597f7fcdee7e537326a2542e8122cf4eed4749c"

  depends_on :fortran
  depends_on 'hepmc'   => :optional
  depends_on 'lhapdf'  => :optional
  depends_on 'homebrew/science/root' => :optional
  depends_on 'homebrew/science/gsl' => :optional

  ENV.delete("F77")

  def install
    args = %W[
      --prefix=#{prefix}
      --enable-shared=no
    ]

    if build.with? "spin2"
      args << "--enable-kk"
      args << "--enable-gsl=#{Formula['gsl'].prefix}"
    end

    args << "--enable-kk"        if build.with? "kk"
    args << "--enable-LHAPDF=#{Formula['lhapdf'].prefix}"	if build.with? "lhapdf"
    args << "--enable-ROOT=#{Formula['root'].prefix}"           if build.with? "root"
    args << "--enable-HEPMC=#{Formula['hepmc'].prefix}"		if build.with? "hepmc"
    args << "--enable-gsl=#{Formula['gsl'].prefix}"		if build.with? "gsl"

    system "./configure", *args
    system "make", "install"
  end

  def caveats; <<-EOS.undent
    Run using:
      vbfnlo --input=PATH/TO/INPUT
      ggflo --input=PATH/TO/INPUT
    EOS
  end

  test do

    system "false"

  end
end
```

**Comment by veprbl** [comment]
```ENV.delete("F77")``` should go after ```def install```

**Comment by cjohnson-phys** [comment]
This appears to have worked!! Thank you so much!! I'll commit soon

**Pull request merged**
