### PR TITLE
mcfm 10.2.2

### PR DESCRIPTION
**Pull request by davidchall**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by andriish** [comment]
Hi @davidchall ,

in addition to the binaries it is nice to install the headers, i.e. patch the CMakeLists.txt with this line:

```
install(DIRECTORY "${CMAKE_SOURCE_DIR}/src/Inc/MCFM" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
```

**Comment by davidchall** [comment]
Error encountered during installation of bundled LHAPDF library:

```
A linker snapshot was created at:
[1034](https://github.com/davidchall/homebrew-hep/actions/runs/3406828591/jobs/5665864289#step:8:1036)
  	/tmp/libLHAPDF.dylib-2022-11-07-012102.ld-snapshot
[1035](https://github.com/davidchall/homebrew-hep/actions/runs/3406828591/jobs/5665864289#step:8:1037)
  ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
```

This error was previously encountered in #285, and is related to a bug in Xcode 14. It looks like GitHub's [macos-12 runner image](https://github.com/actions/runner-images/blob/macOS-12/20221027.1/images/macos/macos-10.15-Readme.md) recently upgraded to Xcode 14

**Comment by davidchall** [comment]
> in addition to the binaries it is nice to install the headers, i.e. patch the CMakeLists.txt with this line:
> 
> ```
> install(DIRECTORY "${CMAKE_SOURCE_DIR}/src/Inc/MCFM" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
> ```
> 
> As those headers are needed by sherpa.

Hi @andriish, I decided not to do it in this PR to keep it dedicated to the version bump. If we want to make MCFM compatible with Sherpa, I think this should have a dedicated PR so we can test it works correctly.

P.S. The [Sherpa manual](https://sherpa.hepforge.org/doc/SHERPA-MC-2.2.13.html#MCFM-interface) describes a script that edits the MCFM source code before installing, so I don't think we can just link Sherpa to the regular MCFM in Homebrew. Instead, we'd need the Sherpa formula to have a dedicated MCFM resource. This is also how the [Rivet formula](https://github.com/davidchall/homebrew-hep/blob/master/Formula/rivet.rb) handles its fjcontrib dependency.

**Comment by davidchall** [comment]
The change to the GitHub Actions needs to be done separately. Closing this PR and will reopen.

**Pull request closed without merging**
